### ISSUE TITLE
Also check for new youtube vids

### ISSUE THREAD

**Issue by CryptKid** [madonius/mi-announce-bot#2]
Youtube provides per-Channel RSS-Feeds, in this case [this one](https://www.youtube.com/feeds/videos.xml?channel_id=UCa8qyXCS-FTs0fHD6HJeyiw) 
It would be nice to query it as well and send notifications (maybe even different ones for "Optisch inkorrekt" and other vids)

**Comment by madonius** [comment]
It's a good idea. The thing that I would try to avoid is the bot being too chatty. First, I would like to implement the core functionality.
